// This file is generated by zbuild. Do not edit manually.

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const dep_zbench = b.dependency("zbench", .{});

    const dep_xev = b.dependency("xev", .{});

    const module_rlp = b.createModule(.{
        .root_source_file = b.path("src/rlp.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("rlp"), module_rlp) catch @panic("OOM");

    const module_enr = b.createModule(.{
        .root_source_file = b.path("src/enr.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("enr"), module_enr) catch @panic("OOM");

    const tls_run_test = b.step("test", "Run all tests");

    const test_rlp = b.addTest(.{
        .name = "rlp",
        .root_module = module_rlp,
        .filters = &[_][]const u8{  },
    });
    const install_test_rlp = b.addInstallArtifact(test_rlp, .{});
    const tls_install_test_rlp = b.step("build-test:rlp", "Install the rlp test");
    tls_install_test_rlp.dependOn(&install_test_rlp.step);

    const run_test_rlp = b.addRunArtifact(test_rlp);
    const tls_run_test_rlp = b.step("test:rlp", "Run the rlp test");
    tls_run_test_rlp.dependOn(&run_test_rlp.step);
    tls_run_test.dependOn(&run_test_rlp.step);

    const test_enr = b.addTest(.{
        .name = "enr",
        .root_module = module_enr,
        .filters = &[_][]const u8{  },
    });
    const install_test_enr = b.addInstallArtifact(test_enr, .{});
    const tls_install_test_enr = b.step("build-test:enr", "Install the enr test");
    tls_install_test_enr.dependOn(&install_test_enr.step);

    const run_test_enr = b.addRunArtifact(test_enr);
    const tls_run_test_enr = b.step("test:enr", "Run the enr test");
    tls_run_test_enr.dependOn(&run_test_enr.step);
    tls_run_test.dependOn(&run_test_enr.step);

    const @"module_enr-bench" = b.createModule(.{
        .root_source_file = b.path("src/enr_bench.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("enr-bench"), @"module_enr-bench") catch @panic("OOM");

    const @"test_enr-bench" = b.addTest(.{
        .name = "enr-bench",
        .root_module = @"module_enr-bench",
        .filters = &[_][]const u8{  },
    });
    const @"install_test_enr-bench" = b.addInstallArtifact(@"test_enr-bench", .{});
    const @"tls_install_test_enr-bench" = b.step("build-test:enr-bench", "Install the enr-bench test");
    @"tls_install_test_enr-bench".dependOn(&@"install_test_enr-bench".step);

    const @"run_test_enr-bench" = b.addRunArtifact(@"test_enr-bench");
    const @"tls_run_test_enr-bench" = b.step("test:enr-bench", "Run the enr-bench test");
    @"tls_run_test_enr-bench".dependOn(&@"run_test_enr-bench".step);
    tls_run_test.dependOn(&@"run_test_enr-bench".step);

    @"module_enr-bench".addImport("enr", b.modules.get("enr") orelse @panic("missing module enr"));
    @"module_enr-bench".addImport("zbench", dep_zbench.module("zbench"));

    _ = dep_xev;
}
